apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: xjiangazureci0603go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xjiangazureci0603go 
  name: xjiangazureci0603go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: xjiangazureci0603go
    weight: 100 
